### ISSUE TITLE
Clippy spending a lot of time in CI checking dependencies? 

### ISSUE THREAD

**Issue by schneems** [heroku/libcnb.rs#532]
Unit tests actually finish much faster than running clippy. It looks like it's checking dependencies by mistake somehow?

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/59744/202951231-b7f95647-b644-45ba-9a70-e9c4ee568344.png">

**Comment by edmorley** [comment]
The cache restore step of that `lint` job says:

```
... Restoring cache ...
No cache found.
```

...whereas the `unit-test` job found/restored a cache.

This explains the time difference.

The reason for this is likely that:
- the cache is only stored when the job succeeds, and this was the first time in four pushes to the branch where linting didn't fail, whereas the test job was passing earlier, so had already stored its cache
- GitHub Actions discards any caches not accessed for 7 days, and the last GitHub Actions run on this repo was 11 days ago

In terms of things to bear in mind with the caching:
- the cache is also invalidated every time the Rust version changes (which happens every 6 weeks)
- for this repo specifically, since it's a library not an application, we intentionally don't commit the `Cargo.lock`, and as such it means the Rust cache plugin can't as efficiently manage the cache (though it's still a net benefit)

Out of curiosity, do you have linting enabled in your IDE? And specifically it set to run `clippy` not `check` as the lint command? I would presume not given the four pushes to get linting to pass? (If using VSCode the default is `check` - and so why https://salesforce.quip.com/geXbAMwRn5Pb suggests changing it.)

**Comment by schneems** [comment]
> Out of curiosity, do you have linting enabled in your IDE? And specifically it set to run clippy not check as the lint command? I would presume not given the four pushes to get linting to pass? (If using VSCode the default is check - and so why https://salesforce.quip.com/geXbAMwRn5Pb suggests changing it.)

My local rust version was older than CI so clippy was passing. It took me a few pushes to figure that out.  My workflow is generally running this https://github.com/schneems/dotfiles/blob/main/bash/aliases#L8 though I tend to push before remembering to run it. So I push, run it, then push again after I've fixed. 

Looking into updating the IDE again.
