### ISSUE TITLE
Docs and Discussion - Code style: When is appropriate to unwrap()/expect() in a buildpack or in libcnb?

### ISSUE THREAD

**Issue by schneems** [heroku/libcnb.rs#603]
In general, it's never a good idea to panic when you can avoid it. Though having proper error handling for things that will either never reasonably error (like regex::Regex being checked by clippy) or likely never error (hard coding in a URL to AWS) is a large overhead. Beyond time and effort, it can create ambiguity over whether or not an error variant is "real" and actionable or if it's simply there for completeness.

I would like to come to a semi-consensus as a group on code style and document it somewhere. 

You could re-write this code:

```rust
fn download_url(stack: &StackId, version: impl std::fmt::Display) -> Result<Url, RubyInstallError> {
    let filename = format!("ruby-{version}.tgz");
    let base = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com";
    let mut url = Url::parse(base).map_err(RubyInstallError::UrlParseError)?;

    url.path_segments_mut()
        .map_err(|_| RubyInstallError::InvalidBaseUrl(String::from(base)))?
        .push(stack)
        .push(&filename);
    Ok(url)
}
```

As this code with except:

```rust
fn download_url(stack: &StackId, version: impl std::fmt::Display) -> Url {
    let mut url = Url::parse("https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com")
        .expect("Internal error: bad url");

    url.path_segments_mut()
        .expect("Internal error: bad url")
        .push(stack)
        .push(&format!("ruby-{version}.tgz"));

    url
}
```

In the second version it's clear that the input is 100% author-controlled. I'm proposing some standards that would help us gauge when this is appropriate and when it isn't.

I suggest we: 

- `unwrap()`
  -  Libcnb/buildpacks: Never use unwrap. If there's an unwrap it should have a code comment with why it's there. 
- `expect()`
  - libcnb/buildpacks: Okay when the code is checked by clippy (i.e. `regex::Regex`)
  - Buildpacks: Okay when there's ar hard-coded programmer input being parsed/manipulated and there are integration tests

What do you think? 

BTW this is an experimental format. I'm trying it out after Ed's comment here https://github.com/heroku/libcnb.rs/pull/589#pullrequestreview-1521604392.

**Comment by edmorley** [comment]
Thank you for raising this. 

Yeah I agree that:
- We should not use `unwrap()` in libcnb/buildpacks (outside of tests), since any valid panic cases should be documented using `expect()`
- Valid cases of using `expect()` in production code (ie: outside of tests/one-off POCs) are when the failure absolutely cannot happen after clippy and unit/integration tests have been run (ie: an internal error that could only be the result of a buildpack bug, and the possibility of that bug can be ruled out by CI)

Ref the download URL example in general - using the `url` crate is possibly overkill for simple domain + path concatenation of tightly controlled strings. If it were rewritten as string interpolation (which is what I use for the Python CNB) it wouldn't involve a `Result`, so no need for `expect()`. (But as an example, it otherwise works fine 🙂)
